[package]
name = "dvine_types"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
encoding_rs.workspace = true
hound.workspace = true
thiserror.workspace = true


[lints]
workspace = true
